import { motion } from 'framer-motion'
import { Edit3, Eye, Plus, Search, Trash2 } from 'lucide-react'
import { useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { usePatient } from '../context/PatientContext'
import StatusBadge from '../components/shared/StatusBadge'
import { AlertDialog } from '../components/ui/alert-dialog'

const patientStatus = (patient) => patient.visits.some((visit) => visit.status === 'in-progress') ? 'Active' : 'Completed'
const date = (value) => new Date(value).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' })
const dataToText = (entries) => entries.map(({ name, detail, severity, brand, generic, drugName, dosage, frequency, activeStatus }) => name ? `${name} | ${detail || severity || 'Not specified'}` : `${drugName || brand} | ${dosage || generic || ''} | ${frequency || ''} | ${activeStatus || 'active'}`).join('\n')

function PatientRecordModal({ patient, onClose }) {
  const profile = [["Diseases", dataToText(patient.diseases)], ["Allergies", dataToText(patient.allergies)], ["Current medications", dataToText(patient.currentMedications)]];
  return <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/40 p-4"><section className="surface mx-auto my-8 max-w-2xl p-6"><h2 className="text-xl font-bold">Patient record: {patient.name}</h2><div className="mt-5 grid gap-4 sm:grid-cols-3"><div className="sm:col-span-2"><p className="text-xs font-medium text-slate-500">Name</p><p className="mt-1 font-semibold">{patient.name}</p></div><div><p className="text-xs font-medium text-slate-500">Age</p><p className="mt-1 font-semibold">{patient.age}</p></div><div className="sm:col-span-3"><p className="text-xs font-medium text-slate-500">Gender</p><p className="mt-1 font-semibold">{patient.gender}</p></div></div><p className="mt-6 text-sm font-bold">Clinical Profile</p><div className="mt-3 grid gap-4 sm:grid-cols-3">{profile.map(([label, value]) => <div key={label}><p className="text-sm font-semibold">{label}</p><p className="mt-1 min-h-24 whitespace-pre-line rounded-lg bg-slate-50 p-3 text-sm dark:bg-slate-700/50">{value || "Not recorded"}</p></div>)}</div><div className="mt-6 flex justify-end"><button type="button" className="btn-secondary" onClick={onClose}>Close</button></div></section></div>
}

export default function Dashboard() {
  const { patients, deletePatientById } = usePatient(); const navigate = useNavigate(); const [query, setQuery] = useState(''); const [status, setStatus] = useState('All'); const [view, setView] = useState('table'); const [viewing, setViewing] = useState(null); const [deleting, setDeleting] = useState(null)
  const stats = useMemo(() => { const allVisits = patients.flatMap((patient) => patient.visits); const today = new Date().toDateString(); return { active: patients.filter((patient) => patientStatus(patient) === 'Active').length, pending: allVisits.filter((visit) => visit.status === 'in-progress').length, today: allVisits.filter((visit) => new Date(visit.date).toDateString() === today).length } }, [patients])
  const filtered = patients.filter((patient) => { const matches = `${patient.name} ${patient.id}`.toLowerCase().includes(query.toLowerCase()); return matches && (status === 'All' || patientStatus(patient) === status) })
  const open = (patient) => navigate(`/patients/${patient.id}`, { state: patientStatus(patient) === 'Active' ? { entry: 'followup' } : undefined })
  const actionButtons = (patient) => <div className="flex justify-end gap-2"><button className="btn-secondary px-3 py-1.5 text-xs" onClick={() => open(patient)}>{patientStatus(patient) === 'Active' ? 'Continue' : 'View'}</button><button aria-label={`View ${patient.name} record`} className="rounded-lg p-2 text-primary hover:bg-primary/10" onClick={() => setViewing(patient)}><Eye size={16} /></button><button aria-label={`Edit ${patient.name}`} className="rounded-lg p-2 text-primary hover:bg-primary/10" onClick={() => navigate('/patients/new', { state: { existingPatientId: patient.id, mode: 'edit' } })}><Edit3 size={16} /></button><button aria-label={`Delete ${patient.name}`} className="rounded-lg p-2 text-danger hover:bg-danger/10" onClick={() => setDeleting(patient)}><Trash2 size={16} /></button></div>
  return <section><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="eyebrow">Patient management</p><h1 className="mt-1 text-3xl font-bold">Patients</h1></div><button onClick={() => navigate('/patients/new')} className="btn-primary"><Plus size={17} />Add New Patient</button></div>
    <div className="mt-7 grid gap-4 sm:grid-cols-3">{[['Active Patients', stats.active], ['Pending Follow-ups', stats.pending], ["Today's Consultations", stats.today]].map(([label, value], index) => <motion.article key={label} initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.3, delay: index * 0.08 }} className="surface border-l-4 border-l-accent p-5"><p className="text-sm text-slate-500 dark:text-slate-300">{label}</p><p className="mt-1 text-3xl font-bold">{value}</p></motion.article>)}</div>
    <div className="surface mt-7 p-4"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div className="flex flex-1 flex-col gap-3 sm:flex-row"><label className="relative flex-1"><Search size={16} className="absolute left-3 top-3 text-slate-400" /><input className="input pl-9" placeholder="Search name or Patient ID" value={query} onChange={(e) => setQuery(e.target.value)} /></label><select className="input sm:w-40" value={status} onChange={(e) => setStatus(e.target.value)}><option>All</option><option>Active</option><option>Completed</option></select></div><div className="flex rounded-lg border border-border p-1 dark:border-slate-600"><button onClick={() => setView('table')} className={`rounded-md px-3 py-1.5 text-sm font-semibold ${view === 'table' ? 'bg-primary text-white' : ''}`}>Table</button><button onClick={() => setView('cards')} className={`rounded-md px-3 py-1.5 text-sm font-semibold ${view === 'cards' ? 'bg-primary text-white' : ''}`}>Cards</button></div></div>
      {!filtered.length ? <div className="py-16 text-center"><p className="font-semibold">No patients found.</p><button onClick={() => navigate('/patients/new')} className="btn-primary mt-4"><Plus size={16} />Add New Patient</button></div> : view === 'table' ? <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead className="border-b border-border text-xs uppercase text-slate-500"><tr>{['Patient ID', 'Name', 'Age', 'Status', 'Last Visit', 'Actions'].map((item) => <th className="p-3" key={item}>{item}</th>)}</tr></thead><tbody>{filtered.map((patient) => <tr key={patient.id} className="border-b border-border/70 dark:border-slate-700"><td className="p-3 font-semibold text-primary">{patient.id}</td><td className="p-3 font-semibold">{patient.name}</td><td className="p-3">{patient.age}</td><td className="p-3"><StatusBadge status={patientStatus(patient)} /></td><td className="p-3">{date(patient.visits.at(-1).date)}</td><td className="p-3">{actionButtons(patient)}</td></tr>)}</tbody></table></div> : <div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filtered.map((patient) => <article className="surface p-5 transition hover:-translate-y-1 hover:shadow-md" key={patient.id}><div className="flex justify-between"><span className="font-bold text-primary">{patient.id}</span><StatusBadge status={patientStatus(patient)} /></div><h2 className="mt-3 text-lg font-bold">{patient.name}</h2><p className="text-sm text-slate-500">Age {patient.age} · Last visit {date(patient.visits.at(-1).date)}</p><div className="mt-5">{actionButtons(patient)}</div></article>)}</div>}</div>
    {viewing && <PatientRecordModal patient={viewing} onClose={() => setViewing(null)} />}{deleting && <AlertDialog open title="Delete patient?" description={`This will remove ${deleting.name} and their visit history.`} onCancel={() => setDeleting(null)} onConfirm={() => { deletePatientById(deleting.id); setDeleting(null) }} />}
  </section>
}
